//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocclientApplication.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/FileService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        PocclientApplication.ServiceReference.CompositeType GetDataUsingDataContract(PocclientApplication.ServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserthousenature", ReplyAction="http://tempuri.org/IService1/InserthousenatureResponse")]
        int Inserthousenature(string nature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selece_nature_id_fromhouse", ReplyAction="http://tempuri.org/IService1/selece_nature_id_fromhouseResponse")]
        int selece_nature_id_fromhouse(int house_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletehousenature", ReplyAction="http://tempuri.org/IService1/DeletehousenatureResponse")]
        int Deletehousenature(string nature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthousenature", ReplyAction="http://tempuri.org/IService1/SelecthousenatureResponse")]
        System.Data.DataSet Selecthousenature();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selecenayureID", ReplyAction="http://tempuri.org/IService1/selecenayureIDResponse")]
        int selecenayureID(string strnature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkhousenature", ReplyAction="http://tempuri.org/IService1/checkhousenatureResponse")]
        int checkhousenature(string strnature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selecenatureID", ReplyAction="http://tempuri.org/IService1/selecenatureIDResponse")]
        string selecenatureID(int strnature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserthousencommonor", ReplyAction="http://tempuri.org/IService1/InserthousencommonorResponse")]
        int Inserthousencommonor(string commonor, string share, string number, string comments, int house_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthousecommonor", ReplyAction="http://tempuri.org/IService1/SelecthousecommonorResponse")]
        System.Data.DataSet Selecthousecommonor([System.ServiceModel.MessageParameterAttribute(Name="Selecthousecommonor")] int Selecthousecommonor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthousecommonortop1", ReplyAction="http://tempuri.org/IService1/Selecthousecommonortop1Response")]
        string Selecthousecommonortop1(int houseid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthousecommonorid", ReplyAction="http://tempuri.org/IService1/SelecthousecommonoridResponse")]
        System.Data.DataSet Selecthousecommonorid(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatacommonor", ReplyAction="http://tempuri.org/IService1/UpdatacommonorResponse")]
        int Updatacommonor(string commonor, string share, string number, string comments, int house_id, int commonorid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletecommonor", ReplyAction="http://tempuri.org/IService1/DeletecommonorResponse")]
        int Deletecommonor(int strcommonorid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserthouse", ReplyAction="http://tempuri.org/IService1/InserthouseResponse")]
        int Inserthouse(
                    string house_word, 
                    string house_number, 
                    string house_owner, 
                    int house_nature_id, 
                    string house_idcardnumber, 
                    string house_located, 
                    string house_dihao, 
                    string house_postscript, 
                    string house_witness, 
                    string house_proofreader, 
                    string house_autograph, 
                    System.DateTime house_licensing_date, 
                    string house_office, 
                    string house_banzhenren, 
                    System.DateTime house_tianfatime, 
                    string house_figure);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatahouse", ReplyAction="http://tempuri.org/IService1/UpdatahouseResponse")]
        int Updatahouse(
                    string house_word, 
                    string house_number, 
                    string house_owner, 
                    int house_nature_id, 
                    string house_idcardnumber, 
                    string house_located, 
                    string house_dihao, 
                    string house_postscript, 
                    string house_witness, 
                    string house_proofreader, 
                    string house_autograph, 
                    System.DateTime house_licensing_date, 
                    string house_office, 
                    string house_banzhenren, 
                    System.DateTime house_tianfatime, 
                    string house_figure, 
                    int houseid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletehouse", ReplyAction="http://tempuri.org/IService1/DeletehouseResponse")]
        int Deletehouse(int strhouseid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthouse", ReplyAction="http://tempuri.org/IService1/SelecthouseResponse")]
        System.Data.DataSet Selecthouse();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthouseid", ReplyAction="http://tempuri.org/IService1/SelecthouseidResponse")]
        System.Data.DataSet Selecthouseid(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthouseiddate", ReplyAction="http://tempuri.org/IService1/SelecthouseiddateResponse")]
        int Selecthouseiddate(string word, string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserthouselocated", ReplyAction="http://tempuri.org/IService1/InserthouselocatedResponse")]
        int Inserthouselocated(string located);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthouselocated", ReplyAction="http://tempuri.org/IService1/SelecthouselocatedResponse")]
        System.Data.DataSet Selecthouselocated();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selece_located_id_fromhouse", ReplyAction="http://tempuri.org/IService1/selece_located_id_fromhouseResponse")]
        int selece_located_id_fromhouse(int house_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectlocatedID", ReplyAction="http://tempuri.org/IService1/selectlocatedIDResponse")]
        int selectlocatedID(string strlocated);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selece_located_id", ReplyAction="http://tempuri.org/IService1/selece_located_idResponse")]
        string selece_located_id(int strlocated);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkhouselocated", ReplyAction="http://tempuri.org/IService1/checkhouselocatedResponse")]
        int checkhouselocated(string strlocated);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertcondition", ReplyAction="http://tempuri.org/IService1/InsertconditionResponse")]
        int Insertcondition(string building_number, string room_number, string jianshu, string building_structure, string cengshu, string built_up_area, string remarks, int house_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectcondition", ReplyAction="http://tempuri.org/IService1/SelectconditionResponse")]
        System.Data.DataSet Selectcondition(int houseid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectconditionid", ReplyAction="http://tempuri.org/IService1/SelectconditionidResponse")]
        System.Data.DataSet Selectconditionid(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatacondition", ReplyAction="http://tempuri.org/IService1/UpdataconditionResponse")]
        int Updatacondition(string building_number, string room_number, string jianshu, string building_structure, string cengshu, string built_up_area, string remarks, int house_id, int conditionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletecondition", ReplyAction="http://tempuri.org/IService1/DeleteconditionResponse")]
        int Deletecondition(int strconditionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserthousedeedtax", ReplyAction="http://tempuri.org/IService1/InserthousedeedtaxResponse")]
        int Inserthousedeedtax(string datetime, string price, string type, string tax_rate, string amount_money, string remarks, int house_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatehousedeedtax", ReplyAction="http://tempuri.org/IService1/UpdatehousedeedtaxResponse")]
        int Updatehousedeedtax(string datetime, string price, string type, string tax_rate, string amount_money, string remarks, int house_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthousedeedtaxid", ReplyAction="http://tempuri.org/IService1/SelecthousedeedtaxidResponse")]
        System.Data.DataSet Selecthousedeedtaxid(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserthouseobligee", ReplyAction="http://tempuri.org/IService1/InserthouseobligeeResponse")]
        int Inserthouseobligee(string obligee, string type, string room_number, string jianshu, string built_up_area, string right_value, string duration_right, string logout_date, int house_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectobligee", ReplyAction="http://tempuri.org/IService1/SelectobligeeResponse")]
        System.Data.DataSet Selectobligee(int house_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectobligeeid", ReplyAction="http://tempuri.org/IService1/SelectobligeeidResponse")]
        System.Data.DataSet Selectobligeeid(int oblid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updataobligee", ReplyAction="http://tempuri.org/IService1/UpdataobligeeResponse")]
        int Updataobligee(string obligee, string type, string room_number, string jianshu, string built_up_area, string right_value, string duration_right, string logout_date, int house_id, int oblid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deleteobligee", ReplyAction="http://tempuri.org/IService1/DeleteobligeeResponse")]
        int Deleteobligee(int strobligeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserthouseuseland", ReplyAction="http://tempuri.org/IService1/InserthouseuselandResponse")]
        int Inserthouseuseland(string use_area, string card_number, int house_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updataohouseuseland", ReplyAction="http://tempuri.org/IService1/UpdataohouseuselandResponse")]
        int Updataohouseuseland(string use_area, string card_number, int house_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthouseuselandid", ReplyAction="http://tempuri.org/IService1/SelecthouseuselandidResponse")]
        System.Data.DataSet Selecthouseuselandid(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthousepicture", ReplyAction="http://tempuri.org/IService1/SelecthousepictureResponse")]
        string Selecthousepicture(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthouselistid", ReplyAction="http://tempuri.org/IService1/SelecthouselistidResponse")]
        System.Data.DataSet Selecthouselistid(string i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthouselistobid", ReplyAction="http://tempuri.org/IService1/SelecthouselistobidResponse")]
        System.Data.DataSet Selecthouselistobid(string i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthouselistusid", ReplyAction="http://tempuri.org/IService1/SelecthouselistusidResponse")]
        System.Data.DataSet Selecthouselistusid(string i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertland", ReplyAction="http://tempuri.org/IService1/InsertlandResponse")]
        int Insertland(
                    string land_tile, 
                    string land_word, 
                    string land_number, 
                    string land_government, 
                    System.DateTime land_date, 
                    string land_user, 
                    string land_idcardnumber, 
                    string land_address, 
                    string land_map, 
                    string land_ground, 
                    string land_use, 
                    string land_use_period, 
                    string land_east, 
                    string land_south, 
                    string land_west, 
                    string land_north, 
                    string land_office, 
                    System.DateTime land_send_date, 
                    string land_remarks, 
                    string land_change_items, 
                    string land_figure);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deleteland", ReplyAction="http://tempuri.org/IService1/DeletelandResponse")]
        int Deleteland(int land_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updataland", ReplyAction="http://tempuri.org/IService1/UpdatalandResponse")]
        int Updataland(
                    string land_tile, 
                    string land_word, 
                    string land_number, 
                    string land_government, 
                    System.DateTime land_date, 
                    string land_user, 
                    string land_idcardnumber, 
                    string land_address, 
                    string land_map, 
                    string land_ground, 
                    string land_use, 
                    string land_use_period, 
                    string land_east, 
                    string land_south, 
                    string land_west, 
                    string land_north, 
                    string land_office, 
                    System.DateTime land_send_date, 
                    string land_remarks, 
                    string land_change_items, 
                    string land_figure, 
                    int land_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectland", ReplyAction="http://tempuri.org/IService1/SelectlandResponse")]
        System.Data.DataSet Selectland();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectlandpicture", ReplyAction="http://tempuri.org/IService1/SelectlandpictureResponse")]
        string Selectlandpicture(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectlandid", ReplyAction="http://tempuri.org/IService1/SelectlandidResponse")]
        int Selectlandid(string land_word, string land_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectlanddateto_edit", ReplyAction="http://tempuri.org/IService1/Selectlanddateto_editResponse")]
        System.Data.DataSet Selectlanddateto_edit(int land_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertcountryside", ReplyAction="http://tempuri.org/IService1/InsertcountrysideResponse")]
        int Insertcountryside(string land_area, string cultivated_land, string dry_land, string paddy_field, string orchard, string forest_land, string grassland, string inmate_mining, string construction_land, string homestead_land, string traffic_land, string water_land, string unused_land, int land_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectcountrysideiddate", ReplyAction="http://tempuri.org/IService1/SelectcountrysideiddateResponse")]
        System.Data.DataSet Selectcountrysideiddate(int land_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatacountryside", ReplyAction="http://tempuri.org/IService1/UpdatacountrysideResponse")]
        int Updatacountryside(string land_area, string cultivated_land, string dry_land, string paddy_field, string orchard, string forest_land, string grassland, string inmate_mining, string construction_land, string homestead_land, string traffic_land, string water_land, string unused_land, int land_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertlandtown", ReplyAction="http://tempuri.org/IService1/InsertlandtownResponse")]
        int Insertlandtown(string land_area, string built_up_area, string common_area, string sharing_area, string land_grade, int land_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatalandtown", ReplyAction="http://tempuri.org/IService1/UpdatalandtownResponse")]
        int Updatalandtown(string land_area, string built_up_area, string common_area, string sharing_area, string land_grade, int land_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectlandtowniddate", ReplyAction="http://tempuri.org/IService1/SelectlandtowniddateResponse")]
        System.Data.DataSet Selectlandtowniddate(int land_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectlandlistcoid", ReplyAction="http://tempuri.org/IService1/SelectlandlistcoidResponse")]
        System.Data.DataSet Selectlandlistcoid(string i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectlandlisttoid", ReplyAction="http://tempuri.org/IService1/SelectlandlisttoidResponse")]
        System.Data.DataSet Selectlandlisttoid(string i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectLoginname", ReplyAction="http://tempuri.org/IService1/SelectLoginnameResponse")]
        string SelectLoginname(string login_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertlogin", ReplyAction="http://tempuri.org/IService1/InsertloginResponse")]
        int Insertlogin(string name, string login_name, string password, string user_right);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selecthouseinquiry", ReplyAction="http://tempuri.org/IService1/SelecthouseinquiryResponse")]
        System.Data.DataSet Selecthouseinquiry(string owner, string idcardnumber, string located, string a2, System.DateTime oldtime, System.DateTime tianfatime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectlandinquiry", ReplyAction="http://tempuri.org/IService1/SelectlandinquiryResponse")]
        System.Data.DataSet Selectlandinquiry(string user, string idcardnumber, string address, System.DateTime oldtime, System.DateTime send_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectconditionhouse_id", ReplyAction="http://tempuri.org/IService1/selectconditionhouse_idResponse")]
        System.Data.DataSet selectconditionhouse_id(string building_structure);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTest", ReplyAction="http://tempuri.org/IService1/DeleteTestResponse")]
        int DeleteTest(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdataTest", ReplyAction="http://tempuri.org/IService1/UpdataTestResponse")]
        int UpdataTest(string strName, string strSex, int intAge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectTest", ReplyAction="http://tempuri.org/IService1/SelectTestResponse")]
        System.Data.DataSet SelectTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Selectloginuser", ReplyAction="http://tempuri.org/IService1/SelectloginuserResponse")]
        System.Data.DataSet Selectloginuser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectLogin", ReplyAction="http://tempuri.org/IService1/SelectLoginResponse")]
        int SelectLogin(string login_name, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectLoginpem", ReplyAction="http://tempuri.org/IService1/SelectLoginpemResponse")]
        string SelectLoginpem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectLogin_id", ReplyAction="http://tempuri.org/IService1/SelectLogin_idResponse")]
        System.Data.DataSet SelectLogin_id(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatalogin", ReplyAction="http://tempuri.org/IService1/UpdataloginResponse")]
        int Updatalogin(int id, string name, string login_name, string password, string user_right);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletelogin", ReplyAction="http://tempuri.org/IService1/DeleteloginResponse")]
        int Deletelogin(int id);
        
        // CODEGEN: 消息 UpFile 的包装名称(UpFile)以后生成的消息协定与默认值(UpLoadFile)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpLoadFile", ReplyAction="http://tempuri.org/IService1/UpLoadFileResponse")]
        PocclientApplication.ServiceReference.UpFileResult UpLoadFile(PocclientApplication.ServiceReference.UpFile request);
        
        // CODEGEN: 消息 DownFile 的包装名称(DownFile)以后生成的消息协定与默认值(DownLoadFile)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownLoadFile", ReplyAction="http://tempuri.org/IService1/DownLoadFileResponse")]
        PocclientApplication.ServiceReference.DownFileResult DownLoadFile(PocclientApplication.ServiceReference.DownFile request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpFile {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long FileSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileStream;
        
        public UpFile() {
        }
        
        public UpFile(string FileName, long FileSize, System.IO.Stream FileStream) {
            this.FileName = FileName;
            this.FileSize = FileSize;
            this.FileStream = FileStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpFileResult", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpFileResult {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public bool IsSuccess;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Message;
        
        public UpFileResult() {
        }
        
        public UpFileResult(bool IsSuccess, string Message) {
            this.IsSuccess = IsSuccess;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownFile {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        public DownFile() {
        }
        
        public DownFile(string FileName) {
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownFileResult", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownFileResult {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long FileSize;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public bool IsSuccess;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileStream;
        
        public DownFileResult() {
        }
        
        public DownFileResult(long FileSize, bool IsSuccess, string Message, System.IO.Stream FileStream) {
            this.FileSize = FileSize;
            this.IsSuccess = IsSuccess;
            this.Message = Message;
            this.FileStream = FileStream;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PocclientApplication.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PocclientApplication.ServiceReference.IService1>, PocclientApplication.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public PocclientApplication.ServiceReference.CompositeType GetDataUsingDataContract(PocclientApplication.ServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public int Inserthousenature(string nature) {
            return base.Channel.Inserthousenature(nature);
        }
        
        public int selece_nature_id_fromhouse(int house_id) {
            return base.Channel.selece_nature_id_fromhouse(house_id);
        }
        
        public int Deletehousenature(string nature) {
            return base.Channel.Deletehousenature(nature);
        }
        
        public System.Data.DataSet Selecthousenature() {
            return base.Channel.Selecthousenature();
        }
        
        public int selecenayureID(string strnature) {
            return base.Channel.selecenayureID(strnature);
        }
        
        public int checkhousenature(string strnature) {
            return base.Channel.checkhousenature(strnature);
        }
        
        public string selecenatureID(int strnature) {
            return base.Channel.selecenatureID(strnature);
        }
        
        public int Inserthousencommonor(string commonor, string share, string number, string comments, int house_id) {
            return base.Channel.Inserthousencommonor(commonor, share, number, comments, house_id);
        }
        
        public System.Data.DataSet Selecthousecommonor(int Selecthousecommonor1) {
            return base.Channel.Selecthousecommonor(Selecthousecommonor1);
        }
        
        public string Selecthousecommonortop1(int houseid) {
            return base.Channel.Selecthousecommonortop1(houseid);
        }
        
        public System.Data.DataSet Selecthousecommonorid(int id) {
            return base.Channel.Selecthousecommonorid(id);
        }
        
        public int Updatacommonor(string commonor, string share, string number, string comments, int house_id, int commonorid) {
            return base.Channel.Updatacommonor(commonor, share, number, comments, house_id, commonorid);
        }
        
        public int Deletecommonor(int strcommonorid) {
            return base.Channel.Deletecommonor(strcommonorid);
        }
        
        public int Inserthouse(
                    string house_word, 
                    string house_number, 
                    string house_owner, 
                    int house_nature_id, 
                    string house_idcardnumber, 
                    string house_located, 
                    string house_dihao, 
                    string house_postscript, 
                    string house_witness, 
                    string house_proofreader, 
                    string house_autograph, 
                    System.DateTime house_licensing_date, 
                    string house_office, 
                    string house_banzhenren, 
                    System.DateTime house_tianfatime, 
                    string house_figure) {
            return base.Channel.Inserthouse(house_word, house_number, house_owner, house_nature_id, house_idcardnumber, house_located, house_dihao, house_postscript, house_witness, house_proofreader, house_autograph, house_licensing_date, house_office, house_banzhenren, house_tianfatime, house_figure);
        }
        
        public int Updatahouse(
                    string house_word, 
                    string house_number, 
                    string house_owner, 
                    int house_nature_id, 
                    string house_idcardnumber, 
                    string house_located, 
                    string house_dihao, 
                    string house_postscript, 
                    string house_witness, 
                    string house_proofreader, 
                    string house_autograph, 
                    System.DateTime house_licensing_date, 
                    string house_office, 
                    string house_banzhenren, 
                    System.DateTime house_tianfatime, 
                    string house_figure, 
                    int houseid) {
            return base.Channel.Updatahouse(house_word, house_number, house_owner, house_nature_id, house_idcardnumber, house_located, house_dihao, house_postscript, house_witness, house_proofreader, house_autograph, house_licensing_date, house_office, house_banzhenren, house_tianfatime, house_figure, houseid);
        }
        
        public int Deletehouse(int strhouseid) {
            return base.Channel.Deletehouse(strhouseid);
        }
        
        public System.Data.DataSet Selecthouse() {
            return base.Channel.Selecthouse();
        }
        
        public System.Data.DataSet Selecthouseid(int id) {
            return base.Channel.Selecthouseid(id);
        }
        
        public int Selecthouseiddate(string word, string number) {
            return base.Channel.Selecthouseiddate(word, number);
        }
        
        public int Inserthouselocated(string located) {
            return base.Channel.Inserthouselocated(located);
        }
        
        public System.Data.DataSet Selecthouselocated() {
            return base.Channel.Selecthouselocated();
        }
        
        public int selece_located_id_fromhouse(int house_id) {
            return base.Channel.selece_located_id_fromhouse(house_id);
        }
        
        public int selectlocatedID(string strlocated) {
            return base.Channel.selectlocatedID(strlocated);
        }
        
        public string selece_located_id(int strlocated) {
            return base.Channel.selece_located_id(strlocated);
        }
        
        public int checkhouselocated(string strlocated) {
            return base.Channel.checkhouselocated(strlocated);
        }
        
        public int Insertcondition(string building_number, string room_number, string jianshu, string building_structure, string cengshu, string built_up_area, string remarks, int house_id) {
            return base.Channel.Insertcondition(building_number, room_number, jianshu, building_structure, cengshu, built_up_area, remarks, house_id);
        }
        
        public System.Data.DataSet Selectcondition(int houseid) {
            return base.Channel.Selectcondition(houseid);
        }
        
        public System.Data.DataSet Selectconditionid(int id) {
            return base.Channel.Selectconditionid(id);
        }
        
        public int Updatacondition(string building_number, string room_number, string jianshu, string building_structure, string cengshu, string built_up_area, string remarks, int house_id, int conditionid) {
            return base.Channel.Updatacondition(building_number, room_number, jianshu, building_structure, cengshu, built_up_area, remarks, house_id, conditionid);
        }
        
        public int Deletecondition(int strconditionid) {
            return base.Channel.Deletecondition(strconditionid);
        }
        
        public int Inserthousedeedtax(string datetime, string price, string type, string tax_rate, string amount_money, string remarks, int house_id) {
            return base.Channel.Inserthousedeedtax(datetime, price, type, tax_rate, amount_money, remarks, house_id);
        }
        
        public int Updatehousedeedtax(string datetime, string price, string type, string tax_rate, string amount_money, string remarks, int house_id) {
            return base.Channel.Updatehousedeedtax(datetime, price, type, tax_rate, amount_money, remarks, house_id);
        }
        
        public System.Data.DataSet Selecthousedeedtaxid(int id) {
            return base.Channel.Selecthousedeedtaxid(id);
        }
        
        public int Inserthouseobligee(string obligee, string type, string room_number, string jianshu, string built_up_area, string right_value, string duration_right, string logout_date, int house_id) {
            return base.Channel.Inserthouseobligee(obligee, type, room_number, jianshu, built_up_area, right_value, duration_right, logout_date, house_id);
        }
        
        public System.Data.DataSet Selectobligee(int house_id) {
            return base.Channel.Selectobligee(house_id);
        }
        
        public System.Data.DataSet Selectobligeeid(int oblid) {
            return base.Channel.Selectobligeeid(oblid);
        }
        
        public int Updataobligee(string obligee, string type, string room_number, string jianshu, string built_up_area, string right_value, string duration_right, string logout_date, int house_id, int oblid) {
            return base.Channel.Updataobligee(obligee, type, room_number, jianshu, built_up_area, right_value, duration_right, logout_date, house_id, oblid);
        }
        
        public int Deleteobligee(int strobligeeid) {
            return base.Channel.Deleteobligee(strobligeeid);
        }
        
        public int Inserthouseuseland(string use_area, string card_number, int house_id) {
            return base.Channel.Inserthouseuseland(use_area, card_number, house_id);
        }
        
        public int Updataohouseuseland(string use_area, string card_number, int house_id) {
            return base.Channel.Updataohouseuseland(use_area, card_number, house_id);
        }
        
        public System.Data.DataSet Selecthouseuselandid(int id) {
            return base.Channel.Selecthouseuselandid(id);
        }
        
        public string Selecthousepicture(int id) {
            return base.Channel.Selecthousepicture(id);
        }
        
        public System.Data.DataSet Selecthouselistid(string i) {
            return base.Channel.Selecthouselistid(i);
        }
        
        public System.Data.DataSet Selecthouselistobid(string i) {
            return base.Channel.Selecthouselistobid(i);
        }
        
        public System.Data.DataSet Selecthouselistusid(string i) {
            return base.Channel.Selecthouselistusid(i);
        }
        
        public int Insertland(
                    string land_tile, 
                    string land_word, 
                    string land_number, 
                    string land_government, 
                    System.DateTime land_date, 
                    string land_user, 
                    string land_idcardnumber, 
                    string land_address, 
                    string land_map, 
                    string land_ground, 
                    string land_use, 
                    string land_use_period, 
                    string land_east, 
                    string land_south, 
                    string land_west, 
                    string land_north, 
                    string land_office, 
                    System.DateTime land_send_date, 
                    string land_remarks, 
                    string land_change_items, 
                    string land_figure) {
            return base.Channel.Insertland(land_tile, land_word, land_number, land_government, land_date, land_user, land_idcardnumber, land_address, land_map, land_ground, land_use, land_use_period, land_east, land_south, land_west, land_north, land_office, land_send_date, land_remarks, land_change_items, land_figure);
        }
        
        public int Deleteland(int land_id) {
            return base.Channel.Deleteland(land_id);
        }
        
        public int Updataland(
                    string land_tile, 
                    string land_word, 
                    string land_number, 
                    string land_government, 
                    System.DateTime land_date, 
                    string land_user, 
                    string land_idcardnumber, 
                    string land_address, 
                    string land_map, 
                    string land_ground, 
                    string land_use, 
                    string land_use_period, 
                    string land_east, 
                    string land_south, 
                    string land_west, 
                    string land_north, 
                    string land_office, 
                    System.DateTime land_send_date, 
                    string land_remarks, 
                    string land_change_items, 
                    string land_figure, 
                    int land_id) {
            return base.Channel.Updataland(land_tile, land_word, land_number, land_government, land_date, land_user, land_idcardnumber, land_address, land_map, land_ground, land_use, land_use_period, land_east, land_south, land_west, land_north, land_office, land_send_date, land_remarks, land_change_items, land_figure, land_id);
        }
        
        public System.Data.DataSet Selectland() {
            return base.Channel.Selectland();
        }
        
        public string Selectlandpicture(int id) {
            return base.Channel.Selectlandpicture(id);
        }
        
        public int Selectlandid(string land_word, string land_number) {
            return base.Channel.Selectlandid(land_word, land_number);
        }
        
        public System.Data.DataSet Selectlanddateto_edit(int land_id) {
            return base.Channel.Selectlanddateto_edit(land_id);
        }
        
        public int Insertcountryside(string land_area, string cultivated_land, string dry_land, string paddy_field, string orchard, string forest_land, string grassland, string inmate_mining, string construction_land, string homestead_land, string traffic_land, string water_land, string unused_land, int land_id) {
            return base.Channel.Insertcountryside(land_area, cultivated_land, dry_land, paddy_field, orchard, forest_land, grassland, inmate_mining, construction_land, homestead_land, traffic_land, water_land, unused_land, land_id);
        }
        
        public System.Data.DataSet Selectcountrysideiddate(int land_id) {
            return base.Channel.Selectcountrysideiddate(land_id);
        }
        
        public int Updatacountryside(string land_area, string cultivated_land, string dry_land, string paddy_field, string orchard, string forest_land, string grassland, string inmate_mining, string construction_land, string homestead_land, string traffic_land, string water_land, string unused_land, int land_id) {
            return base.Channel.Updatacountryside(land_area, cultivated_land, dry_land, paddy_field, orchard, forest_land, grassland, inmate_mining, construction_land, homestead_land, traffic_land, water_land, unused_land, land_id);
        }
        
        public int Insertlandtown(string land_area, string built_up_area, string common_area, string sharing_area, string land_grade, int land_id) {
            return base.Channel.Insertlandtown(land_area, built_up_area, common_area, sharing_area, land_grade, land_id);
        }
        
        public int Updatalandtown(string land_area, string built_up_area, string common_area, string sharing_area, string land_grade, int land_id) {
            return base.Channel.Updatalandtown(land_area, built_up_area, common_area, sharing_area, land_grade, land_id);
        }
        
        public System.Data.DataSet Selectlandtowniddate(int land_id) {
            return base.Channel.Selectlandtowniddate(land_id);
        }
        
        public System.Data.DataSet Selectlandlistcoid(string i) {
            return base.Channel.Selectlandlistcoid(i);
        }
        
        public System.Data.DataSet Selectlandlisttoid(string i) {
            return base.Channel.Selectlandlisttoid(i);
        }
        
        public string SelectLoginname(string login_name) {
            return base.Channel.SelectLoginname(login_name);
        }
        
        public int Insertlogin(string name, string login_name, string password, string user_right) {
            return base.Channel.Insertlogin(name, login_name, password, user_right);
        }
        
        public System.Data.DataSet Selecthouseinquiry(string owner, string idcardnumber, string located, string a2, System.DateTime oldtime, System.DateTime tianfatime) {
            return base.Channel.Selecthouseinquiry(owner, idcardnumber, located, a2, oldtime, tianfatime);
        }
        
        public System.Data.DataSet Selectlandinquiry(string user, string idcardnumber, string address, System.DateTime oldtime, System.DateTime send_date) {
            return base.Channel.Selectlandinquiry(user, idcardnumber, address, oldtime, send_date);
        }
        
        public System.Data.DataSet selectconditionhouse_id(string building_structure) {
            return base.Channel.selectconditionhouse_id(building_structure);
        }
        
        public int DeleteTest(string strName) {
            return base.Channel.DeleteTest(strName);
        }
        
        public int UpdataTest(string strName, string strSex, int intAge) {
            return base.Channel.UpdataTest(strName, strSex, intAge);
        }
        
        public System.Data.DataSet SelectTest() {
            return base.Channel.SelectTest();
        }
        
        public System.Data.DataSet Selectloginuser() {
            return base.Channel.Selectloginuser();
        }
        
        public int SelectLogin(string login_name, string psw) {
            return base.Channel.SelectLogin(login_name, psw);
        }
        
        public string SelectLoginpem(int id) {
            return base.Channel.SelectLoginpem(id);
        }
        
        public System.Data.DataSet SelectLogin_id(int id) {
            return base.Channel.SelectLogin_id(id);
        }
        
        public int Updatalogin(int id, string name, string login_name, string password, string user_right) {
            return base.Channel.Updatalogin(id, name, login_name, password, user_right);
        }
        
        public int Deletelogin(int id) {
            return base.Channel.Deletelogin(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PocclientApplication.ServiceReference.UpFileResult PocclientApplication.ServiceReference.IService1.UpLoadFile(PocclientApplication.ServiceReference.UpFile request) {
            return base.Channel.UpLoadFile(request);
        }
        
        public bool UpLoadFile(string FileName, long FileSize, System.IO.Stream FileStream, out string Message) {
            PocclientApplication.ServiceReference.UpFile inValue = new PocclientApplication.ServiceReference.UpFile();
            inValue.FileName = FileName;
            inValue.FileSize = FileSize;
            inValue.FileStream = FileStream;
            PocclientApplication.ServiceReference.UpFileResult retVal = ((PocclientApplication.ServiceReference.IService1)(this)).UpLoadFile(inValue);
            Message = retVal.Message;
            return retVal.IsSuccess;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PocclientApplication.ServiceReference.DownFileResult PocclientApplication.ServiceReference.IService1.DownLoadFile(PocclientApplication.ServiceReference.DownFile request) {
            return base.Channel.DownLoadFile(request);
        }
        
        public long DownLoadFile(string FileName, out bool IsSuccess, out string Message, out System.IO.Stream FileStream) {
            PocclientApplication.ServiceReference.DownFile inValue = new PocclientApplication.ServiceReference.DownFile();
            inValue.FileName = FileName;
            PocclientApplication.ServiceReference.DownFileResult retVal = ((PocclientApplication.ServiceReference.IService1)(this)).DownLoadFile(inValue);
            IsSuccess = retVal.IsSuccess;
            Message = retVal.Message;
            FileStream = retVal.FileStream;
            return retVal.FileSize;
        }
    }
}
